### ISSUE TITLE
[Vue] - Ubah cara import 3rd party

### ISSUE THREAD

**Issue by mazipan** [hendisantika/vue-crud-nodejs-mongo#1]
Semua kode `import` di lingkungan node.js akan selalu mencari folder node_modules, maka dari itu tidak diperlukan relatif path ke folder ini.

Yang sebelumnya:

```js
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
```

Sebenarnya cukup ditulis

```js
import 'bootstrap/dist/css/bootstrap.min.css'
```

Tanpa adanya relatif path, secara default dimaksudkan ke node_modules.

**Comment by hendisantika** [comment]
Bug Fix - [Vue] - Ubah cara import 3rd party
