### ISSUE TITLE
[Vue] - Belum support route based code splitting

### ISSUE THREAD

**Issue by mazipan** [hendisantika/vue-crud-nodejs-mongo#2]
Salah satu issue terbesar di kode SPA termasuk Vue adalah karena semua file akan di combine jadi satu file, tidak menjadi issue karena baru ada 3 halaman.
Kalau sudah ada 10 halaman aja, ini akan jadi issue besar.
Kode yang sekarang ini memaksakan si user untuk load juga kode halaman lainnya.
Contoh: user lagi di halaman `Create`, secara tidak sengaja mereka juga sebenarnya load juga halaman `Index` dan halaman `Edit`.

Untungnya sebenarnya implementasinya cukup mudah di Vue.
Memanfaatkan `dynamic import`.

Bacaan: https://router.vuejs.org/guide/advanced/lazy-loading.html

Yang sebelumnya 

```js
import Create from '../components/Create';
```

Diubah jadi

```js
const Create = import('../components/Create')
```

**Comment by hendisantika** [comment]
Bug Fix [Vue] - Belum support route based code splitting
